#pragma once

#define E00001	"Could not connect to X Server."
#define E00002	"Your monitor does not support a proper visual mode (RGBA)."
#define E00003	"X Server failed to allocate memory for window title."
#define E00004	"Invalid window parameter. Check xorg.conf for module paths and xorg.log for more information."
#define E00005	"OpenGL could not be intialized."
#define E00006	"Error initializing GLEW. Please install your graphics card drivers."
#define E00007	"An unknown error occured."
#define E00008	"Failed to create vertex shader."
#define E00009	"Failed to create fragment shader."
#define E00010	"Failed to create shader program."
#define E00011	"You seem to be running a version of OpenGL lower than version 3.3 - please update / reinstall your graphics drivers."
#define E00012  "Could not initialize FreeType for font rendering. Contact support."
#define E00013  "Could not load specified font (unknown error)"
